stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags: 
    - shell
  script:
    - cd Backend/Backend
    - mvn package -B
    only:
    refs:
      - master
    changes:
      - Backend/Backend/**/*

maven-test:
  stage: maventest
  tags:
    - shell
  script:
    - cd Backend/Backend
    - mvn test
    - mvn package -B
  artifacts:
    paths:
      - Backend/Backend/target/*.jar

autoDeploy:
  stage: autodeploy
  tags:
    - shell
  script:
    - pkill screen
    - screen
    - java -jar *.jar

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - FRONTEND
  script:
    - cd Frontend
    - .gradlew assemble
  artifacts:
    paths:
      - Frontend/app //here they reference another directory that i don't know about