stages:
    - mavenbuild
    - maventest
    - autodeploy
    - androidbuild
    - androidtest

maven-build:
    stage: mavenbuild
    tags:
        - BACKEND
    script:
        - cd Backend/Backend
        - mvn package -B

maven-test:
    stage: maventest
    tags:
        - BACKEND
    script:
        - cd Backend/Backend
        - mvn test
        - mvn package -B
    artifacts:
        paths:
            - Backend/Backend/*.jar

autoDeploy:
    stage: autodeploy
    tags:
        - BACKEND
    script: 
        - cd Backend/Backend
        - mvn test
        - mvn package -B
        - sudo mv target/*.jar /target/Backend-0.0.1-SNAPSHOT.jar
        - sudo systemctl stop web-demo
        - sudo systemctl start web-demo

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  variables:
    DOCKER_HOST: tcp://localhost:2375
  before_script:
    - export DOCKER_HOST=tcp://localhost:2375
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - FRONTEND
  script:
    - cd Frontend
    - ./gradlew assemble
  artifacts:
    paths:
      - Frontend/ExercyzeFrontend/app/build/outputs/