stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags: 
    - BACKEND
  script:
    - cd Backend/Backend
    - mvn package -B
    only:
    refs:
      - master
    changes:
      - Backend/Backend/**/*

maven-test:
  stage: maventest
  tags:
    - BACKEND
  script:
    - cd Backend/Backend
    - mvn test
    - mvn package -B
  artifacts:
    paths:
      - Backend/Backend/target/*.jar

autoDeploy:
  stage: autodeploy
  tags:
    - BACKEND
  script:
    - cd Backend/test
    - mvn test
    - mvn package -B
    - sudo mv target/test-0.0.1-SNAPSHOT.jar /target/web-demo.jar
    - sudo systemctl stop web-demo
    - sudo systemctl start web-demo

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - FRONTEND
  script:
    - cd Frontend
    - ./gradlew assemble
  artifacts:
    paths:
      - Frontend/app //here they reference another directory that i don't know about